version: '2'
services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"
            - "3003:3003"
            - "4000:4000"
        networks:
            - frontend
        depends_on:
            - php
            - imgserver
            - imgadminserver
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        networks:
            - frontend
            - backend
        environment:
            MYSQL_PASSWORD: "${DOCKER_MYSQL_DB_PASSWORD}"
        depends_on:
            - mysql
    loop:
            build:
                context: .
                dockerfile: ./node/loop/Dockerfile
            networks:
                - backend
            environment:
                       DB_HOST: 'mysql'
                       DB_PORT: '3306'
                       DB_USER: 'root'
                       DB_DATABASE: 'Nodejs'
                       DB_PASSWORD: "${DOCKER_MYSQL_DB_PASSWORD}"
            depends_on:
                - mysql
    imgserver:
                build:
                  context: .
                  dockerfile: ./node/imgServer/Dockerfile
                networks:
                            - frontend
                            - backend
                environment:
                            DB_HOST: 'mysql'
                            DB_PORT: '3306'
                            DB_USER: 'root'
                            DB_DATABASE: 'Nodejs'
                            DB_PASSWORD: "${DOCKER_MYSQL_DB_PASSWORD}"
                depends_on:
                            - mysql

    imgadminserver:
                    build:
                        context: .
                        dockerfile: ./node/imgAdminServer/Dockerfile
                    networks:
                        - frontend
                        - backend
                    environment:
                                DB_HOST: 'mysql'
                                DB_PORT: '3306'
                                DB_USER: 'root'
                                DB_DATABASE: 'Nodejs'
                                DB_PASSWORD: "${DOCKER_MYSQL_DB_PASSWORD}"
                    depends_on:
                        - mysql
    phpmyadmin:
          image: phpmyadmin/phpmyadmin
          ports:
            - "8181:80"
          environment:
            PMA_HOST: mysql
          networks:
                - backend
          depends_on:
               - mysql
    mysql:
        image: mysql:5.7
#        build:
#              context: .
#              dockerfile: ./mysql/Dockerfile
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            DB_USER: 'root'
            MYSQL_ROOT_PASSWORD: "${DOCKER_MYSQL_DB_PASSWORD}"
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
    jenkins:
        image: jenkins:latest
        volumes:
          - jenkins-data:/var/jenkins_home
        ports:
          - "49002:8080"
volumes:
    mysql-data:
    jenkins-data:

networks:
    frontend:
    backend:
